language: python
python:
  - "3.6"
cache: pip
git:
  depth: false

# safelist
branches:
  only:
  - master
  - stable

before_install:
  - apt update
  - apt install  libyaml-dev 
install:
  - pip install -r requirements.txt

script:
  - python3 test.py
