language: python
python:
  - "3.6"
cache: pip
git:
  depth: false

# safelist
branches:
  only:
  - master
  - stable

install:
  - source setup_prerequisites.sh
  - pip install -r requirements.txt

script:
  - python3 test.py
